### ISSUE TITLE
[FLATPAK] Can not open sqlite file using the flatpak app

### ISSUE THREAD

**Issue by williamjmorenor** [flathub/com.github.alecaddd.sequeler#24] opened 2020-05-23 16:32 UTC
Hello I am having issues opening sqlite files with the flatpak package of sequeler as you can see in https://github.com/Alecaddd/sequeler/issues/333 I am not sure if this is a issue with the sandboxing feature of flatpak.

**Comment by bilelmoussaoui** [comment] 2020-05-23 16:37
That's weird, do you get any feedback when you run it form the terminal?

**Comment by williamjmorenor** [comment] 2020-05-23 16:41
This is my output

flatpak run --verbose --filesystem=host:ro com.github.alecaddd.sequeler 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/wmoreno/.local/share/flatpak
F: Opening user flatpak installation at path /home/wmoreno/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/wmoreno/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Allocated instance id 660054000
F: Add values in dir '/com/github/alecaddd/sequeler/', prefix is '/com/github/alecaddd/sequeler/'
F: Add defaults in dir /com/github/alecaddd/sequeler/
F: Add locks in dir /com/github/alecaddd/sequeler/
F: writing D-Conf values to /home/wmoreno/.var/app/com.github.alecaddd.sequeler/config/glib-2.0/settings/keyfile
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 33 xdg-dbus-proxy --args=35'
F: Running 'bwrap --args 33 com.github.alecaddd.sequeler'

**Comment by bilelmoussaoui** [comment] 2020-05-23 16:54
That's the output you're getting when you just open the app or when you try to open a sqlite database file? also, any reason why are you giving it only :ro? sqlite needs to write the lock file and maybe some other stuff on the same location as your database

**Comment by bilelmoussaoui** [comment] 2020-05-26 10:27
The app also uses a `FileChooserNative` which means it shouldn't require home or host permission to just open the database file; seems to be a regression in something else and not in the app itself

**Comment by long21wt** [comment] 2020-08-09 00:48
I couldn't even open the Lollypop (Flatpak version) SQLite database which is located at `/home/me/.var/app/org.gnome.Lollypop/data/lollypop/lollypop.db`. It has the same I/O Error which is mentioned in the issue.

**Comment by long21wt** [comment] 2020-08-09 00:52
Using the package in Fedora repo solves the issue

**Comment by bilelmoussaoui** [comment] 2020-08-09 03:03
Does it work with `--filesystem=host` ?

**Comment by long21wt** [comment] 2020-08-09 13:33
Unfortunately overriding `--filesystem=host` does not work

**Comment by mrguitar** [comment] 2021-04-05 17:42
This is still an issue. I got a bunch of GTK errors when trying this, but I doubt this is the root of the problem.

$ flatpak run --filesystem=host com.github.alecaddd.sequeler
(Sequeler:2): GLib-GObject-WARNING **: 12:34:35.518: g_object_notify: object class 'GtkLabel' has no property named 'rgba'
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_image_set_from_surface: assertion 'GTK_IS_IMAGE (image)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_tree_model_get_iter_first: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_tree_model_get: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_tree_model_iter_next: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_tree_model_filter_refilter: assertion 'GTK_IS_TREE_MODEL_FILTER (filter)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_tree_model_iter_nth_child: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_tree_model_filter_convert_child_iter_to_iter: assertion 'GTK_IS_TREE_MODEL_FILTER (filter)' failed
(Sequeler:2): GLib-GObject-WARNING **: 12:34:35.518: invalid (NULL) pointer instance
(Sequeler:2): GLib-GObject-CRITICAL **: 12:34:35.518: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.518: gtk_combo_box_set_active_iter: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
(Sequeler:2): GLib-GObject-WARNING **: 12:34:35.518: invalid (NULL) pointer instance
(Sequeler:2): GLib-GObject-CRITICAL **: 12:34:35.518: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: _gtk_file_system_get_info: assertion 'GTK_IS_FILE_SYSTEM (file_system)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_image_set_from_surface: assertion 'GTK_IS_IMAGE (image)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_model_get_iter_first: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_model_get: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_model_iter_next: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_list_store_insert: assertion 'GTK_IS_LIST_STORE (list_store)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_list_store_set_valist: assertion 'GTK_IS_LIST_STORE (list_store)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_list_store_insert: assertion 'GTK_IS_LIST_STORE (list_store)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_list_store_set_valist: assertion 'GTK_IS_LIST_STORE (list_store)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: _gtk_bookmarks_manager_get_bookmark_label: assertion 'manager != NULL' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_model_get_path: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_row_reference_new: assertion 'GTK_IS_TREE_MODEL (model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: _gtk_file_system_get_info: assertion 'GTK_IS_FILE_SYSTEM (file_system)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_list_store_set_valist: assertion 'GTK_IS_LIST_STORE (list_store)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_model_filter_refilter: assertion 'GTK_IS_TREE_MODEL_FILTER (filter)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_model_iter_nth_child: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_tree_model_filter_convert_child_iter_to_iter: assertion 'GTK_IS_TREE_MODEL_FILTER (filter)' failed
(Sequeler:2): GLib-GObject-WARNING **: 12:34:35.519: invalid (NULL) pointer instance
(Sequeler:2): GLib-GObject-CRITICAL **: 12:34:35.519: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(Sequeler:2): Gtk-CRITICAL **: 12:34:35.519: gtk_combo_box_set_active_iter: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
(Sequeler:2): GLib-GObject-WARNING **: 12:34:35.519: invalid (NULL) pointer instance
(Sequeler:2): GLib-GObject-CRITICAL **: 12:34:35.519: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

**Comment by wjt** [comment] 2021-09-30 13:59
In the default configuration (without any `--filesystem` overrides) I can reproduce this. I am pretty sure it is because sqlite needs to write another file in the same directory as the database it is opening – but the document portal's FUSE mount does not allow the app to create new files in that directory.

If I place the file into `.var/app/com.github.alecaddd.sequeler/data/` then Sequeler can open it successfully.

(If I run with `--filesystem=home` and try to open the file from `~` then indeed Sequeler crashes as above. But I think the case with the default permissions, i.e. no filesystem access except read-only access to `.ssh` (?), is the one to be concerned with.

**Comment by hfiguiere** [comment] 2021-10-02 17:12
I never got a crash. But I never got the sqlite file to be open.

BTW the package has been updated to the latest upstream.

**Comment by wjt** [comment] 2021-10-04 20:52
https://github.com/flatpak/xdg-desktop-portal/issues/463#issuecomment-604541561 is highly relevant!

**Comment by bilelmoussaoui** [comment] 2024-04-21 12:28
This should be fixed now, it was a portal issue

**Closed by bilelmoussaoui** 2024-04-21 12:29 UTC
